//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Start_time { get; set; }
        public System.TimeSpan End_time { get; set; }
        public string Channel { get; set; }
        public int Click { get; set; }
        public bool Most_clicked { get; set; }
        public bool Editor_recommendation { get; set; }
        public string Picture { get; set; }
    }
}
