//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program_Credits
    {
        public int Id { get; set; }
        public string Role_Firstname { get; set; }
        public string Role_Lastname { get; set; }
        public int Credits_id { get; set; }
        public int Program_id { get; set; }
    
        public virtual Credits Credits { get; set; }
        public virtual Program Program { get; set; }
    }
}
